"""Add ondelete CASCADE to messages foreign key

Revision ID: 06e2d1abb3e4
Revises: 5eba963e8853
Create Date: 2025-09-18 18:28:37.732331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e2d1abb3e4'
down_revision: Union[str, Sequence[str], None] = '5eba963e8853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_companion_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'companions', ['companion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_companion_id_fkey'), 'messages', 'companions', ['companion_id'], ['id'])
    # ### end Alembic commands ###
