"""Add ondelete CASCADE to messages table

Revision ID: 5eba963e8853
Revises: 4b6468cfa921
Create Date: 2025-09-18 16:12:57.163921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eba963e8853'
down_revision: Union[str, Sequence[str], None] = '4b6468cfa921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
