"""Add avatar_url to User and Companion models

Revision ID: 9bc3c17cce4f
Revises: a7e1e20b3629
Create Date: 2025-10-05 13:42:20.163994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bc3c17cce4f'
down_revision: Union[str, Sequence[str], None] = 'a7e1e20b3629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companions', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('companions', sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='AI伙伴头像URL，存储在COS上'))
    op.alter_column('companions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_companions_user_id'), table_name='companions')
    op.create_index(op.f('ix_companions_owner_id'), 'companions', ['owner_id'], unique=False)
    op.drop_constraint(op.f('companions_user_id_fkey'), 'companions', type_='foreignkey')
    op.create_foreign_key(None, 'companions', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('companions', 'src')
    op.drop_column('companions', 'user_id')
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment='用户头像URL，存储在COS上',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='用户头像URL，存储在COS上',
               existing_nullable=True)
    op.add_column('companions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('companions', sa.Column('src', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companions', type_='foreignkey')
    op.create_foreign_key(op.f('companions_user_id_fkey'), 'companions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_companions_owner_id'), table_name='companions')
    op.create_index(op.f('ix_companions_user_id'), 'companions', ['user_id'], unique=False)
    op.alter_column('companions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('companions', 'avatar_url')
    op.drop_column('companions', 'owner_id')
    # ### end Alembic commands ###
