# .github/workflows/ci.yml (最终完美版)

name: AI Companion CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install uv
          # 注意：我们在这里也需要安装 aiosqlite，所以要同步 dev 依赖
          uv pip sync requirements.txt requirements-dev.txt

      - name: Run tests with pytest
        # 关键：确保 env: 部分存在，并且包含了所有需要的密钥
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEEPSEEK_API_BASE: ${{ secrets.DEEPSEEK_API_BASE }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          # 关键：确保 DATABASE_URL 使用了 aiosqlite 驱动
          DATABASE_URL: "sqlite+aiosqlite:///./test.db"

        run: |
          source .venv/bin/activate
          pytest